// Full performance report: every table in NUMBERS.md comes from one run of this script.
//
//   npm run build && npx vite preview --port 4317 &
//   npm run report -- http://localhost:4317/
//
// Runs headless Chrome (puppeteer-core + local Chrome) against:
//   <url>naive/   the frozen v0 build            → naive ramp to its breaking point
//   <url>         the optimised build            → each optimisation toggled on in turn, culling zoomed in, final ceiling
import puppeteer from 'puppeteer-core';

const CHROME = process.env.CHROME || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const WARMUP_MS = +(process.env.WARMUP_MS || 2000); // let spawning/GC settle, then reset the stats window
const MEASURE_MS = +(process.env.MEASURE_MS || 5000);
const base = (process.argv[2] || 'http://localhost:4317/').replace(/\/?$/, '/');

const browser = await puppeteer.launch({
  executablePath: CHROME,
  headless: true,
  args: ['--enable-precise-memory-info', ...(process.env.CHROME_ARGS ? process.env.CHROME_ARGS.split(' ') : [])],
  defaultViewport: { width: 1440, height: 900 },
});
const page = await browser.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const HEAD = '| Build [flags] | E/T/P | FPS | p95 ms | ≥45 FPS % | >33 ms % | sim ms | render ms | heap MB |\n|---|---|---|---|---|---|---|---|---|';

async function measure(setup, arg) {
  await page.evaluate(setup, arg);
  await sleep(WARMUP_MS);
  await page.evaluate(() => resetStats());
  await sleep(MEASURE_MS);
  return page.evaluate(() => statsRow());
}

const ua = await browser.version();
console.log(`_${ua}, headless, 1440×900. Each row: ${WARMUP_MS / 1000} s warm-up, then a ${MEASURE_MS / 1000} s measurement window. Generated by \`npm run report\`._\n`);

// 1. Naive ramp
await page.goto(base + 'naive/', { waitUntil: 'networkidle0' });
console.log('### Naive build (v0) — finding the breaking point\n\n' + HEAD);
for (const c of [[1000, 30, 300], [2000, 50, 500], [3000, 75, 750], [3500, 85, 850], [4000, 90, 900], [5000, 100, 1000]]) {
  console.log(await measure((c) => game.startStress({ enemies: c[0], towers: c[1], projectiles: c[2] }), c));
}

// 2. Optimisations switched on one at a time (cumulative), on the same scenario
await page.goto(base, { waitUntil: 'networkidle0' });
const ORDER = ['useGrid', 'usePool', 'useTargetCache', 'useSprites', 'useBgCache', 'useCulling'];
for (const c of [[2000, 50, 500], [5000, 100, 1000]]) {
  console.log(`\n### Optimisations added one at a time — ${c.join('/')}\n\n` + HEAD);
  for (let k = 0; k <= ORDER.length; k++) {
    const on = ORDER.slice(0, k);
    console.log(await measure(({ on, c }) => {
      for (const f of Object.keys(flags)) flags[f] = on.includes(f);
      ui.syncFlags();
      cam.zoom = 1;
      cam.clamp();
      game.startStress({ enemies: c[0], towers: c[1], projectiles: c[2] });
    }, { on, c }));
  }
}

// 3. Culling only matters when part of the world is off screen: zoom to 3x
console.log('\n### Viewport culling at 3× zoom — 5000/100/1000\n\n' + HEAD);
for (const cull of [false, true]) {
  console.log(await measure((cull) => {
    for (const f of Object.keys(flags)) flags[f] = true;
    flags.useCulling = cull;
    ui.syncFlags();
    game.startStress({ enemies: 5000, towers: 100, projectiles: 1000 });
    cam.zoom = 3;
    cam.clamp();
  }, cull));
}

// 4. Ablation near the ceiling: everything on, then each optimisation switched OFF on its own.
//    Shows what each one contributes once the others are in place.
console.log('\n### Ablation — all on, then one switched off — 12000/200/3000\n\n' + HEAD);
for (const off of [null, ...ORDER]) {
  console.log(await measure((off) => {
    for (const f of Object.keys(flags)) flags[f] = f !== off;
    ui.syncFlags();
    cam.zoom = 1;
    cam.clamp();
    game.startStress({ enemies: 12000, towers: 200, projectiles: 3000 });
  }, off));
}

// 5. Final ceiling, everything on
console.log('\n### Final build — ceiling\n\n' + HEAD);
for (const c of [[5000, 100, 1000], [10000, 200, 3000], [12000, 200, 3000], [14000, 200, 3000], [16000, 200, 3000], [16000, 270, 8000]]) {
  console.log(await measure((c) => {
    for (const f of Object.keys(flags)) flags[f] = true;
    ui.syncFlags();
    cam.zoom = 1;
    cam.clamp();
    game.startStress({ enemies: c[0], towers: c[1], projectiles: c[2] });
  }, c));
}

if (errors.length) console.log('\nPage errors:', errors);
await browser.close();
